name: 'Build and Push Multi-Arch Image'

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'release-*'
    tags:
      - 'v*'

concurrency:
  group: march-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  image-build:
    uses: konveyor/release-tools/.github/workflows/build-push-images.yaml@main
    with:
      registry: "quay.io/konveyor"
      image_name: "static-report"
      containerfile: "./Dockerfile"
      architectures: '[ "amd64", "arm64", "ppc64le", "s390x" ]'
      extra-args: "--build-arg VERSION=${{ github.ref_name }}"
    secrets:
      registry_username: ${{ secrets.QUAY_PUBLISH_ROBOT }}
      registry_password: ${{ secrets.QUAY_PUBLISH_TOKEN }}
